curl -s -X POST https://js-scanner.onrender.com/scan \
  -H "Content-Type: application/json" \
  -d '{"url":"https://dotv3n.github.io/javascriptsecret/","same_origin_only":false,"ignore_robots":true}'
